spring:
  application:
    name: game-server

  ai:
    openai:
      api-key: 'sk-proj-poeZwZyraHUyec63Am25T3BlbkFJwkwCzAeq50DXVQLHMH96'

kafka:
  bootstrap-server: ${KAFKA_HOST}
  producer:
    end-game-topic: "end-game"

server:
  name: ${SERVER_NAME}
  port: ${SERVER_PORT}

scheduler:
  cron:
    end-game: '*/10 * * * * *' #every 10 seconds
